README.rst, utils/README.rst, utils/aiadm-move-files.sh
=> utils: aiadm-move-files

README.rst, atlas-2016-outreach/README.rst, atlas-2016-outreach/code/1-eos-get-listings.sh
* Initial release of helper scripts for preparing the ATLAS 2016 outreach
release.
=> atlas-2016-outreach: initial release

README.rst, atlas-2016-masterclasses/README.rst, atlas-2016-masterclasses/code/1-eos-get-listings.sh
* Initial release of helper scripts for preparing the ATLAS 2016 masterclasses
release.
=> atlas-2016-masterclasses: initial release

LICENSE, README.rst
=> docs: license and badges

README.rst
=> docs: badge order and author link update

.travis.yml, README.rst, run-tests.sh, utils/README.rst, utils/update_fixtures.py
* Adds fixture updater that permits to work with JSON record files.
(closes #2)
* Adds basic Travis CI initial configuration.
=> utils: update_fixtures.py

README.rst
=> docs: link fix

cms-YYYY-simulated-datasets/code/dataset_records.py
* See https://github.com/cernopendata/opendata.cern.ch/issues/2497
=> cms-YYYY-simulated-datasets: pileup information and links

utils/README.rst, utils/update_checksums.py
* Addresses cernopendata/opendata.cern.ch#2528
=> utils: update_checksums

cms-YYYY-simulated-datasets/code/dataset_records.py
=> records: fix configuration titles

cms-YYYY-simulated-datasets/code/dataset_records.py
* references https://github.com/cernopendata/opendata.cern.ch/issues/2466
* closes #36
=> records: add ondemand field

cms-YYYY-simulated-datasets/code/dataset_records.py
=> cms-YYYY-simulated-datasets: fix created date methodology description

utils/merge_delete_fixtures.py
The script is able to manipulate fixture records: concatenate and later delete them.
=> Merge fixture fields

cms-YYYY-simulated-datasets/code/conffiles_records.py, cms-YYYY-simulated-datasets/code/das_json_store.py, cms-YYYY-simulated-datasets/code/dataset_records.py, cms-YYYY-simulated-datasets/code/mcm_store.py, cms-YYYY-simulated-datasets/code/printer.py
* Improves CMS MC provenance gathering information chain. (closes #44)
=> cms-YYYY-simulated-datasets: provenance fixes

utils/create_eos_file_indexes.py
=> utils: create EOS file indexes and optional file pattern

utils/update_checksums.py
=> utils: update_checksums check-only mode

cms-2011-simulated-datasets/code/update_generator_information.py
Script for https://github.com/cernopendata/opendata.cern.ch/pull/2712
=> cms-2011-simulated-datasets: update generator information

README.rst, cms-2010-collision-datasets/code/update_hlt_trigger_information_record.py, cms-2010-collision-datasets/run.sh
* Script for https://github.com/cernopendata/opendata.cern.ch/pull/2738
Signed-off-by: Tibor Šimko <tibor.simko@cern.ch>
=> cms-2010-collision-datasets: HLT trigger information

cms-run2-hlt-triggers/inputs/summary2016.txt, cms-run2-hlt-triggers/inputs/summary2017.txt, cms-run2-hlt-triggers/inputs/summary2018.txt
Closes #107 
Adds hlt summaries for 2016-2018
=> Add summary files 2016-2018

cms-2015-collision-datasets/code/create_cms_2015_collision_datasets.py
Closes cernopendata/opendata.cern.ch#3212.
=> cms-2015-collision-datasets: usage info update

.github/workflows/cms-luminosity-tables.yaml
=> fix lumi worlflow yaml

cms-YYYY-luminosity/code/lumi_records.py
=> cms-YYYY-luminosity: fix lumi record json field types

cms-YYYY-simulated-datasets/code/categorisation.py
(closes #142)
Updates the script to take into account the new MC for Run2
=> cms-YYYY-simulated-datsets: update for missing categories

cms-2011-simulated-datasets/code/convert_methodology_description_to_steps.py
* Converting the html description to json structure (Closes #27)
=> script: converting methodology.description to methodology.steps

cms-YYYY-validated-runs/README.md, cms-YYYY-validated-runs/code/vali_records.py
(addresses #145)
Updates the script for #169 and modifies it for HI-related data taking.
It can now be used to build validated runs record for 2013 HI release
=> cms-YYYY-validated-runs: update for HI records

.github/workflows/cms-luminosity-tables.yaml, cms-YYYY-luminosity/README.md, cms-YYYY-luminosity/code/lumi_records.py, cms-YYYY-luminosity/commands.sh
Updates the scripts and workflows to take into account different types of data taking.
Tested for inputs given in readme (up to 2015)
=> cms-YYYY-luminosity: update scripts for HI type data taking

.github/workflows/ci.yml, run-tests.sh, utils/create_eos_file_indexes.py, utils/generate_dois.py, utils/merge_delete_fixtures.py, utils/update_checksums.py, utils/update_fixtures.py, utils/update_ondemand.py
switched to using black instead of pycodestyle:
- reformatted all `utils/*.py ` files using black
- modified `run-tests.sh` to do a black check instead of a pycodestyle one
- modified `.github/workflows/ci.yml` to plug the new black test in
=> tests: upgrade to using black instead of pycodestyle

cms-2015-collision-datasets/code/create_cms_2015_collision_datasets.py, cms-2015-collision-datasets/code/create_hlt_config_file_records.py, cms-2015-collision-datasets/code/create_hlt_trigger_information_record.py, cms-2015-collision-datasets/code/create_hlt_trigger_path_records.py
Includes HI run triggers.
Excludes Special and Cosmic triggers.
Adds information about 2015G runs.
=> cms-2015-collision-datasets: include HI run triggers

cms-release-info/cms_release_container_images_info.json
Adds the HI container images to the helper
=> cms-release-info: add new hi container images

cms-2015-collision-datasets-hi-ppref/inputs/CMSDatasetDescription_Run2015E.csv
Complete the description and removed the two FIXMEs
=> cms-2015-collision-datasets-hi-ppref: complete description

README.rst
Completes top-level README file with links to all data-curation campaigns.
=> docs: add links to all curation campaigns

cms-2016-collision-datasets/code/create_cms_2016_collision_datasets.py
Closes cernopendata/opendata.cern.ch#3540
=> cms-2016-collision-datasets: fix HLT trigger path links

jade-2023-raw-datasets/code/create_cn_records.py, jade-2023-raw-datasets/inputs/ComputingNotes.txt, jade-2023-raw-datasets/run.sh
Add creation files for JADE computing notes #228
=> Add creation files for JADE computing notes
